security:
  firewalls:
    spotifyAuth:
      pattern: ^/(auth|authCallback)
      provider: spotifyUserProvider
      guard:
        authenticators:
          - App\Security\SpotifyAuthenticator
    main:
      pattern: ^/
#      anonymous: lazy
      logout: ~
      provider: userProvider
      guard:
        authenticators:
          - App\Security\Authenticator

  providers:
    userProvider:
      id: App\Security\UserProvider
    spotifyUserProvider:
      id: App\Security\SpotifyUserProvider