security:
  firewalls:
    main:
      pattern: ^/
#      anonymous: lazy
      stateless: true
      logout: ~
      guard:
        authenticators:
          - App\Security\Authenticator

  providers:
    spotifyUserProvider:
      id: App\Security\UserProvider