version: '3.3'

services:
    php:
        # You need to have already build the image
        image: cemalklc/phpfpm-nginx:latest
        build: .
        volumes:
            # use delegated mode here on docker for mac for faster disk I/O
            - .:/var/www/app:delegated
            - ./docker/nginx-site.conf:/etc/nginx/conf.d/default.conf
        entrypoint: /usr/local/bin/docker-php-entrypoint-dev
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
        ports:
            - "8081:80"
            - "8443:443"
            - "9001:9001"
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_NAME:-dummy}
            DB_USERNAME: ${DB_USER:-dummy}
            DB_PASSWORD: ${DB_PASSWORD:-secret}

    mysql:
        image: mysql:5.7
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_NAME:-dummy}
            MYSQL_USER: ${DB_USER:-dummy}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
            
# using this named volume ensures db's hang around between "up's"
volumes:
    mysql:

