#!/bin/sh
set -e

# write the php-fpm config
{ \

    echo listen = /var/run/php-fpm.sock; \
    echo listen.owner = www-data; \
    echo listen.group = www-data; \
    echo listen.mode = 0660; \

    echo user = www-data; \
    echo group = www-data; \

    echo ping.path = /ping; \
    echo pm.status_path = /status; \
    echo pm.max_children = "$FPM_PM_MAX_CHILDREN"; \
    echo pm.start_servers = "$FPM_PM_START_SERVERS"; \
    echo pm.min_spare_servers = "$FPM_PM_MIN_SPARE_SERVERS"; \
    echo pm.max_spare_servers = "$FPM_PM_MAX_SPARE_SERVERS"; \

    echo catch_workers_output = yes; \

    echo php_flag[display_errors] = on; \
    echo php_admin_value[error_log] = /var/log/php-fpm.www.log; \
    echo php_admin_flag[log_errors] = on; \
} > /usr/local/etc/php-fpm.d/zzz-app.conf

exec "$@"
