
index:
  methods: GET
  path: /
  controller: App\Controller\IndexController::index

# just a place holder for now
authCallback:
  methods: GET
  path: /authCallback

playlists:
  path: /playlists
  controller: App\Controller\PlaylistController::getUserPlaylists

playlist-create:
  path:       /playlist
  controller: App\Controller\PlaylistController::createTindifyPlaylist
  methods:    POST

add-song-to-playlist:
  path:       /playlist/{id}/songs
  controller: App\Controller\PlaylistController::addSongsToPlaylist
  methods:    POST

get-playlist-songs:
  path:       /playlist/{id}/songs
  controller: App\Controller\PlaylistController::getPlaylistSongs
  methods:    GET


## Song related
get-recommended-songs:
  path:       /song/recommendations
  controller: App\Controller\SongController::getRecommendations
  methods:    POST

get-a-song:
  path:       /song/{id}
  controller: App\Controller\SongController::getSong
  methods:    GET
