
index:
  methods: GET
  path: /
  controller: App\Controller\IndexController::index

## Spotify Auth Endpoints - START

# just a place holder for now
authCallback:
  methods: GET
  path: /authCallback
auth:
  methods: GET
  path: /auth

## Spotify Auth Endpoints - END

playlists:
  path:       /playlists
  controller: App\Controller\PlaylistController::getUserPlaylists
  methods:    GET

playlist-create:
  path:       /playlists
  controller: App\Controller\PlaylistController::createTindifyPlaylist
  methods:    POST

add-song-to-playlist:
  path:       /playlists/{id}/songs
  controller: App\Controller\PlaylistController::addSongsToPlaylist
  methods:    POST

get-playlist-songs:
  path:       /playlists/{id}/songs
  controller: App\Controller\PlaylistController::getPlaylistSongs
  methods:    GET


## Song related
get-recommended-songs:
  path:       /songs/recommendations
  controller: App\Controller\SongController::getRecommendations
  methods:    POST

get-a-song:
  path:       /songs/{id}
  controller: App\Controller\SongController::getSong
  methods:    GET
