
# just a place holder for now
authCallback:
  methods: GET
  path: /authCallback

playlists:
  path: /playlists
  controller: App\Controller\PlaylistController::getUserPlaylists

playlist-create:
  path:       /playlist
  controller: App\Controller\PlaylistController::createTindifyPlaylist
  methods:    POST

add-song-to-playlist:
  path:       /playlist/{id}/songs
  controller: App\Controller\PlaylistController::addSongsToPlaylist
  methods:    POST